export const ERC20_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address owner) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 value) returns (bool)",
  "function transfer(address to, uint256 value) returns (bool)",
  "function transferFrom(address from, address to, uint256 value) returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)"
];

export const VAULT_ABI = [
  "function stakeADS(uint256 amount, uint256 periodDays) external",
  "function stakeUSDT(uint256 amountUsdt) external",
  "function claimAdsRewards() external",
  "function claimUsdtRewards() external",
  "function withdrawAdsPrincipal(uint256 stakeId) external",
  "function calculatePendingAdsReward(address user, uint256 stakeId) view returns (uint256)",
  "function calculatePendingUsdtReward(address user, uint256 stakeId) view returns (uint256)",
  "function userStakedADS(address user) view returns (uint256)",
  "function userTotalStakedUsdt(address user) view returns (uint256)",
  "function isParticipant(address user) view returns (bool)",
  "function getUserAdsStakesCount(address user) view returns (uint256)",
  "function getUserUsdtStakesCount(address user) view returns (uint256)",
  "function userAdsStakes(address user, uint256 index) view returns (uint256 stakeId, uint256 amount, uint256 periodDays, uint256 dailyRoiBps, uint256 startTime, uint256 maturityTime, uint256 claimedRewards, uint256 lastClaimTime, bool isMatured, bool principalWithdrawn)",
  "function userUsdtStakes(address user, uint256 index) view returns (uint256 stakeId, uint256 amountUsdt, uint256 startTime, uint256 maxRewardUsdt, uint256 claimedRewardsUsdt, uint256 lastClaimTime, bool isCompleted)",
  "function isInstantTestnetMode() view returns (bool)",
  "function testnetInstantAddDaysReward(uint256 stakeId, uint256 daysCount) external",
  "function testnetInstantFillUsdtCap(uint256 stakeId) external",
  "function testnetInstantMatureStake(uint256 stakeId) external",
  "function setProductionMode() external",
  "function setInstantTestnetMode(bool _instant) external",
  "event AdsStaked(address indexed user, uint256 indexed stakeId, uint256 amount, uint256 periodDays, uint256 dailyRoiBps)",
  "event UsdtStaked(address indexed user, uint256 indexed stakeId, uint256 amountUsdt, uint256 maxRewardCap)",
  "event AdsRewardsClaimed(address indexed user, uint256 netReward, uint256 taxDeducted)",
  "event UsdtRewardsClaimed(address indexed user, uint256 netReward, uint256 taxDeducted)",
  "event AdsPrincipalWithdrawn(address indexed user, uint256 indexed stakeId, uint256 amount)"
];
